<a href="https://colab.research.google.com/github/Wilmot2025/Java_Test/blob/main/numpy%20basic22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
l = [[1,2,3]]
arr=np.array(l)
print (arr)
print(arr.ndim)
print(arr.shape)

[[1 2 3]]
2
(1, 3)


In [ ]:
import numpy as np
l = [[1,2,3], [4,5,6]]
arr=np.array(l)
print (arr)
print(arr.ndim)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [ ]:
import numpy as np
l = [[[1,2,3]], [[4,5,6]],[[7,8,9]],[[10,11,12]]]
arr=np.array(l)
print (arr)
print(arr.ndim)
print(arr.shape)

[[[ 1  2  3]]

 [[ 4  5  6]]

 [[ 7  8  9]]

 [[10 11 12]]]
3
(4, 1, 3)


In [ ]:
import numpy as np
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [ ]:
import numpy as np
arr = np.linspace(0,5,5)
print(arr)

[0.   1.25 2.5  3.75 5.  ]


In [ ]:
import numpy as np
l = np.logspace(1,5,5)
print(l)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]


In [ ]:
import numpy as np
l = np.zeros(5)
print(l)

[0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
l = np.eye(3)
print(l)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
l = np.eye(2,3)
print(l)

[[1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
import numpy as np
l = np.logspace(1,5,5)
print(l)

In [ ]:
import numpy as np
l1 = np.full((2,3),7)
print(l)

[[1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
import numpy as np
l2 = np.full((2,2,3,),5)
print(l)

[[1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
import numpy as np
l1 = np.identity(4)
print(l)

[[1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
import numpy as np
arr1 = np.random.randint(1,10,3)
print(arr1)

[1 3 5]


In [ ]:
import numpy as np
arr1 = np.random.randint(5,15,(2,3))
print(arr1)

[[ 5  8  6]
 [13 14  6]]


In [ ]:
import numpy as np
arr1 = np.random.randn(6)
print(arr1)

[-0.19929933 -1.14511376  1.09395821 -1.59646107 -0.15986287  0.06007059]


In [ ]:
import numpy as np
arr2 = np.random.randn(2,3)
print(arr2)

[[-0.08917259  1.78683051 -1.4722237 ]
 [-0.46572209  0.68145634 -2.42515095]]


In [ ]:
import numpy as np
arr3 = np.random.rand(3,2,2)
print(arr3)

[[[0.21728008 0.82808968]
  [0.68930572 0.36785457]]

 [[0.55578829 0.52174347]
  [0.62603831 0.95003792]]

 [[0.15958552 0.15806552]
  [0.80053802 0.78650081]]]


In [ ]:
import numpy as np
arr1 = np.random.randn(3)
print(arr1)

[-1.44031219  0.70516953  0.99208027]


In [ ]:
import numpy as np
arr = np.random.randint(1,50,10)
print(arr)

[ 7 34 36 38 31  4 25  4 31 24]


In [ ]:
import numpy as np
arr1 = arr.reshape(2,5)
print(arr1)

[[ 7 34 36 38 31]
 [ 4 25  4 31 24]]


In [ ]:
#reshaping 1d to 2d
import numpy as np
arr1 = np.random.randint(1,50,10)
print(arr)
arr1 = arr.reshape(2,5)
print(arr1)

[ 7 34 36 38 31  4 25  4 31 24]
[[ 7 34 36 38 31]
 [ 4 25  4 31 24]]


In [ ]:
#reshaping 1d to 3d
import numpy as np
arr = np.random.randint(1,50,20) # This generates a new arr1, but its value is overwritten next.
print(arr)
arr1 = arr.reshape(2,5,2) # Corrected: Reshaping 'arr' (10 elements) into a 2x5 array (10 elements).
print(arr1)
arr2 = arr.reshape(10) # Corrected: Reshaping 'arr' (10 elements) into a 1D array of 10 elements.


[ 7 34 36 38 31  4 25  4 31 24]
[[ 7 34 36 38 31]
 [ 4 25  4 31 24]]


In [ ]:
import numpy as np
np.random.seed(123)
arr = np.random.randint(1,50,10)
print(arr)


[46  3 29 35 39 18 20 43 23 34]


In [ ]:
import numpy as np
np.random.seed(123)
arr = np.random.randint(1,100,20).reshape(2,10)
print(arr)
print(arr.ndim)
print(arr.size)

[[67 93 99 18 84 58 87 98 97 48]
 [74 33 47 97 26 84 79 37 97 81]]
2
20


In [ ]:
num = int(input("Enter a number: "))
original = num
digits = len(str(num))
result = 0

for i in str(num):
    result += int(i) ** digits

if result == original:
    print("Armstrong Number")
else:
    print("Not an Armstrong Number")

Enter a number: 10000
Not an Armstrong Number


In [ ]:
num = int(input("Enter a number: "))
original = num
digits = len(str(num))
result = 0

while num > 0:
    digit = num % 10
    result += digit ** digits
    num //= 10

if result == original:
    print("Armstrong Number")
else:
    print("Not an Armstrong Number")

Enter a number: 12
Not an Armstrong Number


In [ ]:
num = int(input("Enter a number: "))

for i in range(1, 11):
    print(num, "x", i, "=", num * i)

5 x 1 = 5
5 x 2 = 10
5 x 3 = 15


In [23]:
num = int(input("Enter a number: "))
total = 0

while num > 0:
    digit = num % 10
    total += digit
    num //= 10

print("Sum of digits:", total)

Enter a number: 60
Sum of digits: 6


In [24]:
# Ask the user to enter their name
name = input("Enter your name: ")

# Count characters (excluding spaces)
name_without_spaces = name.replace(" ", "")
count = len(name_without_spaces)

# Display in required format
print(str(count) + ". Character: " + str(count))

Enter your name: Wilmot T Okai
11. Character: 11


In [30]:
# Print number pattern

for i in range(5, 0, -1):
    for j in range(i, 0, -1):
        print(j, end=" ")
    print()

5 4 3 2 1 
4 3 2 1 
3 2 1 
2 1 
1 


In [16]:
import numpy as np
print(2 + np.ones((3,3)))

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [18]:
import numpy as np
arr3 = np.array([[3,3,3],[3,3,3],[3,3,3]])
print(arr3)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [13]:
import numpy as np
arr = np.array([3,3,3])
print(arr)

[3 3 3]


In [15]:
import numpy as np
arr3 = np.array([[[3,3,3],[3,3,3],[3,3,3]]])
print(arr3)

[[[3 3 3]
  [3 3 3]
  [3 3 3]]]


In [10]:
import numpy as np
num = int(input("Enter a number: "))

for i in range(1,3):
    print(num, "i", "=", num *i)

Enter a number: 3
3 i = 3
3 i = 6


In [20]:
import numpy as np

# Create first 3x3 matrix
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Create second 3x3 matrix
matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

# Find the sum
matrix_sum = matrix1 + matrix2

# Display results
print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nSum of the matrices:")
print(matrix_sum)

Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Sum of the matrices:
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [21]:
import numpy as np

# Create first matrix
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Create second matrix
matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

# Multiply matrices
result = np.dot(matrix1, matrix2)

# Display results
print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nMultiplication Result:")
print(result)

Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Multiplication Result:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [22]:
import numpy as np

# Generate random 5x5 matrix (values between 0 and 1)
matrix = np.random.rand(5, 5)

print("Original Matrix:")
print(matrix)

# Replace values
matrix[matrix > 0.5] = 1
matrix[matrix <= 0.5] = 0

print("\nModified Matrix:")
print(matrix)

Original Matrix:
[[0.48316528 0.77916808 0.91301439 0.22092215 0.15447262]
 [0.93577737 0.26395334 0.95407206 0.6445606  0.96161813]
 [0.83608738 0.0919125  0.77982049 0.87470257 0.67922878]
 [0.76665049 0.47250552 0.57371422 0.60032419 0.75869613]
 [0.46760002 0.37681173 0.49311352 0.18232809 0.51455442]]

Modified Matrix:
[[0. 1. 1. 0. 0.]
 [1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [0. 0. 0. 0. 1.]]


In [2]:
import numpy as np

arr = np.array([1, 2, 3,])
print(arr)

[1 2 3]


In [4]:
import numpy as np

arr = np.zeros([1, 2, 3,])
print(arr)

[[[0. 0. 0.]
  [0. 0. 0.]]]


In [8]:
import numpy as np

arr = np.ones([1, 2, 3,])
print(arr)

[[[1. 1. 1.]
  [1. 1. 1.]]]


In [14]:
import numpy as np

arr = np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


In [22]:
import numpy as np

arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [25]:
import numpy as np

arr = np.random.rand(2, 2)
print(arr)

[[0.71435197 0.94110013]
 [0.39019301 0.88340538]]


In [26]:
import numpy as np

arr = np.random.randint(1, 10,(2, 3))
print(arr)

[[9 2 5]
 [2 2 4]]


In [33]:
import numpy as np

arr = np.full((2, 2,3), 7)
print(arr)

[[[7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]]]


In [40]:
import numpy as np
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
